using UnityEngine;
using UnityEngine.AI;

public class EnemyAI : MonoBehaviour
{

	public NavMeshAgent agent;

	public Transform player;

	public LayerMask whatIsGround, whatIsPlayer;
    
    //Patrolling
    public Vector3 walkPoint;
    bool walkPointSet;
    public float walkPointRange;

    //Attacking
    public float timeBetweenAttacks;
    bool alreadyAttacked;

    //States
    public float sightRange, attackRange;
    public bool playerInSightRange, playerInAttackRange;

    private void Awake()
    {
    	player = GameObject.Find("Player2").transform;
    	agent = GetComponent<NavMeshAgent>();
    }

    private void Update(){

    	playerInSightRange = Physics.CheckSphere(transform.position, sightRange, whatIsPlayer);
    	playerInAttackRange = Physics.CheckSphere(transform.position, attackRange, whatIsPlayer);

    	if(!playerInSightRange && !playerInAttackRange) Patrolling();
    	if(playerInSightRange && !playerInAttackRange) ChasePlayer();
    	if(playerInSightRange && playerInAttackRange) AttackPlayer();

    }
    
    
    private void Patrolling(){

    	if(!walkPointSet) SearchWalkPoint();

    	if(walkPointSet)
    		agent.SetDestination(walkPoint);

    	Vector3 distanceToWalkPoint = transform.position - walkPoint;

    	//Walkpoint reached
    	if (distanceToWalkPoint.magnitude < 1f)
    		walkPointSet = false;
    }

	private void SearchWalkPoint(){

		float randomZ = Random.Range(-walkPointRange, walkPointRange);
		float randomX = Random.Range(-walkPointRange, walkPointRange);

		walkPoint = new Vector3(transform.position.x + randomX, transform.position.y, transform.position.z + randomZ);

		if (Physics.Raycast(walkPoint, -transform.up, 2f, whatIsGround))
			walkPointSet = true;

	}

	private void ChasePlayer(){

		agent.SetDestination(player.position);
  
    }


    private void AttackPlayer(){

    }
}
